//using System;

//namespace Exceptions
//{
//    class Program
//    {
//        static void Main(string[] args)
//        {
//            MyList<int> list = new MyList<int>();
            //list.Add(1);
            //list.Add(2);
            //list.Add(3);
            //list.Add(3);
            //list.Add(3);
            //list.Add(3);
            //list.Add(3);
            //list.Add(3);
            //list.Add(3);
            //list.Add(3);
            //list.Add(4);

            //list.Clear();
            //list.Add(4);

            //list.GetAll();

            //List<int> nums = new List<int> { 1,2,3,4,5,6,7 };
            //list.AddRange(nums);
            //list.GetAll();

            //MyList<string> list2 = new MyList<string>();
            //list2.Add("1");
            //list2.Add("2");
            //list2.Add("3");
            //list2.Add("4");

            //var result = list2.Find(m => m == "1");
            //Console.WriteLine(result);

//        }
//    }
//}